config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "main#index"

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "password", to: "password#edit"
  patch "password", to: "password#update"

  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"
  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "sign_in", to: "session#new"
  post "sign_in", to: "session#create"

  delete "logout", to: "session#destroy"
  get "/about", to: "about#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
# email: string
# password_digest:string

# password: virtual
# password_confirmation:string virtual
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :password_confirmation, presence: true
    validates :password, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user 
    
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must sign in to do that." if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
    before_action :require_user_logged_in!

    def edit 
    
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "password updated"
        else  
            render :edit
        end
    end

    private
    
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController

    def new 
    end

    def create
        @user = User.find_by(email: params[:email]);

        if @user.present?
            PasswordMailer.with(user: @user).reset.deliver_now
        end

        redirect_to root_path, notice: "We're send you to this email"
    end

    def edit 
        @user = User.find_signed!(params[:token], purpose: "password_reset")

        rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Token expired!"
    end

    def update 
        @user = User.find_signed!(params[:token], purpose: "password_reset")

        if @user.update(password_params)
            redirect_to sign_in_path, notice: "your password was reset successfully, please sign in"
        else 
            render :edit
        end
    end

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id;
            redirect_to root_path, notice: "Successfully created account"
        else
            flash[:alert] = "Something was wrong !"
            render :new 
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def new

    end

    def create
        user = User.find_by(email: params[:email])

        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id 
            redirect_to root_path, notice: "Login successfully"
        else
            flash[:alert] = "invalid email / password"
            render :new
        end
    end

    def destroy 
        session[:user_id] = nil
        redirect_to root_path, notice: "Successfully logout"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main Page</h1>

app/views/password/edit.html.erb
<h6>Change Password</h6>

<%= form_with model: Current.user, url: password_path do |form| %>
    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |message| %>
                <div> <%= message %> </div>
            <% end %>
        </div>
    <% end %>

    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "enter your password" %>
    </div>

    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "enter your password confirmation" %>
    </div>

    <div>
        <%= form.submit "Update Password", data: { turbo: false }, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/password_reset/edit.html.erb
<h6> Reset Password </h6>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <% if @user.errors.any? %>
        <div class="alert alert-danger">
            <% @user.errors.full_messages.each do |message| %>
                <div> <%= message %> </div>
            <% end %>
        </div>
    <% end %>
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "enter your password" %>
    </div>

    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "enter your password confirmation" %>
    </div>

    <div>
        <%= form.submit "Reset", data: { turbo: false }, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/password_reset/new.html.erb
<h6> Forgot the password ? </h6>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
        <%= form.label "Email" %>
        <%= form.text_field "email", class: "form-control", placeholder: "enter your email" %>
    </div>

    <div>
        <%= form.submit "Reset", data: { turbo: false }, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/session/new.html.erb
<h1>Sign In </h1>

<%= form_with url: sign_in_path do | form | %>
    <div class="mb-3">
        <%= form.label "Email" %>
        <%= form.text_field "email", class: "form-control", placeholder: "Enter your email" %>
    </div>

    <div class="mb-3">
        <%= form.label "Password" %>
        <%= form.password_field "password", class: "form-control", placeholder: "Enter your password" %>
        <%= link_to "forgot password ?", password_reset_path %>
    </div>

    <div>
        <%= form.submit "Sign in", data: { turbo: false }, class: "btn btn-primary col-12" %>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-info mt-4">
    <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-warning mt-4">
    <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Schedule Tweets", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0"> 
        <% if Current.user %>
            <li class="nav-link">
              <%= link_to Current.user.email, password_path, class: "nav-link" %>
            </li>
            <li class="nav-link">
              <%= button_to "Logout", logout_path, method: :delete %>
            </li>
        <% else %>
            <li class="nav-link">
              <%= link_to "Login", sign_in_path, class: "nav-link" %>
            </li>
            <li class="nav-link">
              <%= link_to "Sign up", sign_up_path, class: "nav-link" %>
            </li>
        <% end %>
      </ul> 
    </div>

   
  </div>
</nav>